image: "python:3.7"
services:
  - mysql:5.7

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - checking

before_script:
  - ./build.sh

Build:
  stage: checking
  script:
    - python3 src/manage.py migrate
  tags:
    - shell
